### ISSUE TITLE
buffer allocated is too small

### ISSUE THREAD

**Issue by eco747** [adafruit/Adafruit-PN532#107] opened 2023-01-04 11:29 UTC
in writecommand, the buffer is not correctly allocated

```c
void Adafruit_PN532::writecommand(uint8_t *cmd, uint8_t cmdlen) {
  if (spi_dev != NULL) {
    // SPI command write.
    uint8_t checksum;
    uint8_t packet[8 + cmdlen];  <<<<<<<<<<<< here, should be 8+cmdLen+1
    uint8_t *p = packet;
    cmdlen++;                            <<<<<<<<<<<< because of this

```

**Comment by caternuson** [comment] 2023-02-20 20:57
Closing. This is a dupe of #106.

**Closed by caternuson** 2023-02-20 20:57 UTC
